version: '3.3'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=dev_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teamosaira@08
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql-volume:/var/lib/postgresql/data